// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeGAUg901hALjzLIyGBGjClyPiELXLa-0',
    appId: '1:801648575514:web:de2b3c909ec250ac143da3',
    messagingSenderId: '801648575514',
    projectId: 'classactivity14-133e6',
    authDomain: 'classactivity14-133e6.firebaseapp.com',
    storageBucket: 'classactivity14-133e6.firebasestorage.app',
    measurementId: 'G-LS1REER8B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMR98j_3BvrWzRfGv2vgQzR6s7Kzj0rgo',
    appId: '1:801648575514:android:8e5e8395c9dbd552143da3',
    messagingSenderId: '801648575514',
    projectId: 'classactivity14-133e6',
    storageBucket: 'classactivity14-133e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7OG2p051pMk6aPeYAtM8fx3rJrd886rU',
    appId: '1:801648575514:ios:8c16a936b9ca8ddf143da3',
    messagingSenderId: '801648575514',
    projectId: 'classactivity14-133e6',
    storageBucket: 'classactivity14-133e6.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7OG2p051pMk6aPeYAtM8fx3rJrd886rU',
    appId: '1:801648575514:ios:8c16a936b9ca8ddf143da3',
    messagingSenderId: '801648575514',
    projectId: 'classactivity14-133e6',
    storageBucket: 'classactivity14-133e6.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeGAUg901hALjzLIyGBGjClyPiELXLa-0',
    appId: '1:801648575514:web:b3d3eec7cc7a4f2f143da3',
    messagingSenderId: '801648575514',
    projectId: 'classactivity14-133e6',
    authDomain: 'classactivity14-133e6.firebaseapp.com',
    storageBucket: 'classactivity14-133e6.firebasestorage.app',
    measurementId: 'G-3QZWJJFL9H',
  );
}
